GET http://localhost:5000/notes

###

POST http://localhost:5000/tambah-note
Content-Type: application/json

{
    "title": "Tugas 2 Prak TCC",
    "content": "Tugas 2 Prak TCC (Disuruh GCP bjirrr)",
    "is_finish": 0
}

###

PUT http://localhost:5000/update-note/3
Content-Type:  application/json

{
    "title": "Tugas 3 Prak TCC",
    "content": "Tugas 3 Prak TCC",
    "is_finish": 1
}

###

DELETE  http://localhost:5000/delete-note/3